<div class="topo-table">
    <!--<a class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>-->
    <a href="<?php echo $this->url('contatos', array('action' => 'novo')) ?>" 
       class="btn btn-success" title="Novo">
        <span class="glyphicon glyphicon-plus"></span>
    </a>
    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default"><?php echo $this->itens_pagina; ?></button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <?php foreach (['005', '010', '025', '050', '100'] as $value): ?>
                <li class="<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>">
                    <a href="<?php echo $this->url('contatos', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_nome' => $coluna_nome, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]]) ?>">
                        <?php echo $value; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <form class="form-inline pull-right" role="form">
        <div class="form-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" name="search" value="<?php echo $this->search; ?>" class="form-control typeahead" id="localizar" placeholder="Bucar..." autocomplete="off">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />

<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <thead>
<!--            <tr>
                <th>Nº Registro</th>
                <th>Nome</th>
                <th>Tel. Principal</th>
                <th>Qtde. Tel.</th>
                <th>Data Criação</th>  
                <th>Ação</th>  
            </tr>-->
            <?php echo $this->partial('partial/colunas_sort'); ?>            
        </thead>

        <tbody>
            <?php foreach ($this->contatos as $contato) : ?>
                <tr>
                    <td class="text-center"><?php echo $this->filter($contato)->id(); ?></td>
                    <td><?php echo $this->escapeHtml($contato->name); ?></td>
                    <td class="text-center"><?php echo $this->escapeHtml($contato->fone1); ?></td>
                    <td class="text-center"><?php echo $this->filter($contato)->quantidadeTelefones(); ?></td>
                    <td><?php echo $this->escapeHtml($contato->created); ?></td>
                    <td>
                        <button class="btn btn-xs btn-info" data-toggle="modal" data-target="#modal-detalhes-contato" data-contato-url="<?php echo $this->url('contatos', array("action" => "detalhes", "id" => $contato->id)); ?>" title="Visualizar" >
                            <span class="glyphicon glyphicon-new-window"></span></button>
                        <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('contatos', array("action" => "editar", "id" => $contato->id,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                        <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('contatos', array("action" => "deletar", "id" => $contato->id,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
// controle de paginação
    echo $this->paginationControl(
            // objeto contentdo os contatos
            $this->contatos,
            // tipo de style da paginação
            'Sliding',
            // partial que vai conter o html da paginação
            [/* path */ 'partial/paginator.phtml', /* modulo */ 'Contato'],
            // link rotas da paginação
            ['route' => 'contatos']
    );
    ?>
    <div class="modal fade" id="modal-detalhes-contato">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    Corpo Modal Detalhes Contato
                </div>
            </div>
        </div>    
    </div>
    <?php $this->headScript()->captureStart(); ?>
    $(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('contatos', array("action" => "deletar")); ?>' + '/';

    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
    // variável contendo o id referente ao botão clicado
    var contato_id  = $(this).attr('href').split(url_deletar).pop();
    // variável contendo mensagem da janela
    var mensagem = "Deseja realmente apagar o contato de ID " + contato_id + "?";
    // variável com resposta da mensagem colocada na janela
    var confirmacao = confirm(mensagem);

    // se a confirmação for false o fluxo é interrompido
    if (!confirmacao)
    // elimar o evendo do botão clicado
    event.preventDefault();
    });
    });

    $(function(){
    $('#modal-detalhes-contato').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)             // Button that triggered the modal
    var contato_url = button.data('contato-url')    // Extract info from data-* attributes

    var modal = $(this)
    modal.
    find('.modal-body').        // localizar corpo modal
    html('Carregando...').      // colocar html caso a requição demore
    load(contato_url)           // inserir conteudo html AJAX
    })
    });    
    <?php $this->headScript()->captureEnd(); ?>