<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$env = getenv('APP_ENV') ? : 'development';

$modules = array(
    'Contato',
);
if ($env == 'development') {
    $modules[] = 'ZendDeveloperTools';
    $modules[] = 'BjyProfiler';
}

return array(
//    'modules' => array(
//        'Contato',
//        'ZendDeveloperTools',
//        'BjyProfiler',
//    ),
    'modules' => $modules,
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
        ),
    ),
    'config_cache_enabled' => false,
    'config_cache_key' => 'app_config',
    'module_map_cache_enabled' => ($env == 'development'),
    'module_map_cache_key' => 'module_map',
    'cache_dir' => './data/cache',
    'check_dependencies' => ($env != 'development'),
    'service_manager' => array(
        'factories' => array(
            'Zend\Cache\StorageFactory' => function() {
                return Zend\Cache\StorageFactory::factory(
                                array(
                                    'adapter' => array(
                                        'name' => 'filesystem',
                                        'options' => array(
                                            'dirLevel' => 2,
                                            'cacheDir' => 'data/cache',
                                            'dirPermission' => 0755,
                                            'filePermission' => 0666,
//                                'namespaceSeparator' => '-db-'
                                        ),
                                    ),
                                    'plugins' => array('serializer'),
                                )
                );
            }
                ),
                'abstract_factories' => array(
                    'Zend\Cache\Service\StorageCacheAbstractServiceFactory',
                ),
                'aliases' => array(
                    'cache' => 'Zend\Cache\StorageFactory',
                ),
            ),
        );
        